### ISSUE TITLE
Bossmenu

### ISSUE THREAD

**Issue by DanTVx** [TigoDevelopment/esx_customJobs#1]
Dear Tigo,

Where can i find the boss menu?
or how do i add the boss menu?

I really like the script and currently using it but cant get a bossmenu in it 

hope you can help me

**Comment by TigoDevelopment** [comment]
I will add those options this week

**Comment by DanTVx** [comment]
Awesome Thanks :D

**Comment by DanTVx** [comment]
Any idea wich day it comes?
