### ISSUE TITLE
Job selection

### ISSUE THREAD

**Issue by namikoglu** [TigoDevelopment/esx_customJobs#2]
Hey. Couldnt find any INSERT INTO jobs in sql so i will ask this, can we use esx_joblisting to choose jobs or?

**Comment by namikoglu** [comment]
And i just noticed, no items?

**Comment by TigoDevelopment** [comment]
This project isn't finished, there will be missing functions. You should make changes to scripts yourself if you want to make them work with some other scripts. I can't support you in that.
